import { useEffect, useRef, useState, useCallback } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import mermaid from 'mermaid'
import { marked } from 'marked'
import TurndownService from 'turndown'
// @ts-expect-error — no types published for this plugin
import { gfm } from 'turndown-plugin-gfm'
import { ChevronDown } from 'lucide-react'
import type { Components } from 'react-markdown'
import type { HLDSection, HLDDocument, Comment } from '@/types'
import { CommentSection } from './CommentSection'
import styles from './DocumentPanel.module.css'

// ---------------------------------------------------------------------------
// Markdown ↔ HTML helpers for the WYSIWYG editor
// ---------------------------------------------------------------------------
const td = new TurndownService({ headingStyle: 'atx', bulletListMarker: '-', codeBlockStyle: 'fenced' })
td.use(gfm)   // adds GFM table, strikethrough, tasklist rules

function mdToHtml(md: string): string {
  return marked.parse(md, { async: false }) as string
}

function htmlToMd(html: string): string {
  return td.turndown(html)
}

// ---------------------------------------------------------------------------
// Inline Mermaid block — used inside ReactMarkdown's code renderer
// ---------------------------------------------------------------------------
let inlineMermaidCounter = 0

function InlineMermaid({ code }: { code: string }) {
  const containerRef = useRef<HTMLDivElement>(null)
  const [error, setError] = useState(false)

  useEffect(() => {
    const id = `inline-mermaid-${++inlineMermaidCounter}`
    if (!containerRef.current) return

    mermaid.render(id, code)
      .then(({ svg }) => {
        if (containerRef.current) {
          containerRef.current.innerHTML = svg
        }
      })
      .catch(() => setError(true))
  }, [code])

  if (error) {
    return <pre className={styles.mermaidFallback}>{code}</pre>
  }

  return <div ref={containerRef} className={styles.inlineMermaid} />
}

// ---------------------------------------------------------------------------
// Custom code renderer — detects mermaid fences
// ---------------------------------------------------------------------------
const markdownComponents: Components = {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  code({ className, children, ...props }: any) {
    const match = /language-(\w+)/.exec(className || '')
    const lang = match ? match[1] : ''
    const code = String(children).replace(/\n$/, '')

    if (lang === 'mermaid') {
      return <InlineMermaid code={code} />
    }

    // Block code (has className) vs inline code
    if (className) {
      return (
        <pre className={styles.codeBlock}>
          <code className={className} {...props}>{children}</code>
        </pre>
      )
    }

    return <code className={styles.inlineCode} {...props}>{children}</code>
  },
}

// Strip internal quality-check callouts (Reviewer challenge / Self-evaluation)
// generated by the LLM prompt — these are prompt artefacts, not document content.
const REVIEWER_RE = /^>?\s*⚠️\s*\*{0,2}Reviewer challenge:?\*{0,2}.*$/gim

function stripInternalCallouts(content: string): string {
  return content.replace(REVIEWER_RE, '').replace(/\n{3,}/g, '\n\n').trim()
}

// ---------------------------------------------------------------------------
// DocumentPanel
// ---------------------------------------------------------------------------
interface DocumentPanelProps {
  hld: HLDDocument
  onSectionEdit?: (key: string, newContent: string) => void
  /** Key of section to scroll into view (from a chat edit) */
  scrollToKey?: string | null
  /** Called once the scroll has been triggered, so parent can clear the key */
  onScrolled?: () => void
  reviewId?: string | null
  comments?: Comment[]
  canComment?: boolean
  onCommentsChange?: () => void
  /** Called when the visible section changes while scrolling (scroll spy) */
  onActiveSectionChange?: (key: string) => void
}

export function DocumentPanel({
  hld,
  onSectionEdit,
  scrollToKey,
  onScrolled,
  reviewId,
  comments = [],
  canComment = false,
  onCommentsChange,
  onActiveSectionChange,
}: DocumentPanelProps) {
  const [editingKey, setEditingKey]   = useState<string | null>(null)
  const [draftContent, setDraftContent] = useState('')    // markdown (for save)
  const editableRef = useRef<HTMLDivElement | null>(null) // contenteditable DOM node
  const [collapsed, setCollapsed] = useState<Record<string, boolean>>({})
  const [highlightedKey, setHighlightedKey] = useState<string | null>(null)
  const sectionRefs = useRef<Record<string, HTMLDivElement | null>>({})

  // Scroll to and highlight a section when scrollToKey changes
  useEffect(() => {
    if (!scrollToKey) return
    const el = sectionRefs.current[scrollToKey]
    if (el) {
      // Ensure expanded
      setCollapsed(prev => ({ ...prev, [scrollToKey]: false }))
      el.scrollIntoView({ behavior: 'smooth', block: 'start' })
      setHighlightedKey(scrollToKey)
      const timer = setTimeout(() => setHighlightedKey(null), 2500)
      onScrolled?.()
      return () => clearTimeout(timer)
    }
  }, [scrollToKey, onScrolled])

  // Scroll spy — notify parent of the topmost visible section
  useEffect(() => {
    if (!onActiveSectionChange) return
    const observers: IntersectionObserver[] = []
    // Track which sections are currently visible, pick topmost
    const visible = new Map<string, number>()  // key → section number

    const flush = () => {
      if (visible.size === 0) return
      const top = [...visible.entries()].sort((a, b) => a[1] - b[1])[0][0]
      onActiveSectionChange(top)
    }

    for (const [key, el] of Object.entries(sectionRefs.current)) {
      if (!el) continue
      const section = hld.sections.find(s => s.key === key)
      if (!section) continue
      const obs = new IntersectionObserver(
        ([entry]) => {
          if (entry.isIntersecting) { visible.set(key, section.number); flush() }
          else { visible.delete(key); flush() }
        },
        { rootMargin: '-10% 0px -60% 0px', threshold: 0 },
      )
      obs.observe(el)
      observers.push(obs)
    }
    return () => observers.forEach(o => o.disconnect())
  // Re-run when sections change; sectionRefs are stable within a render pass
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [hld.sections, onActiveSectionChange])

  const toggleSection = (key: string) =>
    setCollapsed(prev => ({ ...prev, [key]: !prev[key] }))

  const startEdit = (section: HLDSection) => {
    setCollapsed(prev => ({ ...prev, [section.key]: false }))
    setEditingKey(section.key)
    setDraftContent(section.content)  // keep markdown as fallback
  }

  const saveEdit = (key: string) => {
    const html = editableRef.current?.innerHTML ?? ''
    const md = html.trim() ? htmlToMd(html) : draftContent
    onSectionEdit?.(key, md)
    setEditingKey(null)
  }

  const cancelEdit = () => setEditingKey(null)

  const setRef = useCallback((key: string) => (el: HTMLDivElement | null) => {
    sectionRefs.current[key] = el
  }, [])

  return (
    <div className={styles.doc}>
      {/* ── Document header ── */}
      <div className={styles.docHeader}>
        <div className={styles.docBadge}>
          <span>Enriched Requirement Document — Technical</span>
          <span className={styles.docBadgeSep}>·</span>
          <span className={styles.docBadgeSub}>{hld.template}</span>
        </div>
        <h1 className={styles.docTitle}>{hld.project_name}</h1>
      </div>

      {hld.sections.map(section => {
        const isCollapsed  = !!collapsed[section.key]
        const isEditing    = editingKey === section.key
        const isHighlighted = highlightedKey === section.key
        return (
          <div
            key={section.key}
            ref={setRef(section.key)}
            className={`${styles.section} ${isCollapsed ? styles.sectionCollapsed : ''} ${isHighlighted ? styles.sectionHighlighted : ''}`}
          >
            {/* ── Section title row: number · title · [edit/save/cancel] · collapse ── */}
            <div className={styles.sectionTitleRow}>
              <span className={styles.sectionNum}>{section.number}.</span>
              <h2 className={styles.sectionTitle}>{section.title}</h2>
              {/* Inline edit controls — appear on hover (or always when editing) */}
              {isEditing ? (
                <div className={styles.titleEditActions}>
                  <button className={styles.cancelBtn} onClick={e => { e.stopPropagation(); cancelEdit() }}>Cancel</button>
                  <button className={styles.editBtn} onClick={e => { e.stopPropagation(); saveEdit(section.key) }}>Save</button>
                </div>
              ) : (
                <button
                  className={styles.editBtn}
                  onClick={e => { e.stopPropagation(); startEdit(section) }}
                  aria-label="Edit section"
                >
                  Edit
                </button>
              )}
              <button
                onClick={() => toggleSection(section.key)}
                aria-expanded={!isCollapsed}
                className={styles.sectionHead}
              >
                <ChevronDown
                  size={15}
                  className={`${styles.chevron} ${isCollapsed ? styles.chevronClosed : ''}`}
                />
              </button>
            </div>

            {/* ── Body — hidden when collapsed ── */}
            {!isCollapsed && (
              <div className={styles.sectionBody}>
                {isEditing ? (
                  <div
                    ref={editableRef}
                    className={`${styles.sectionContent} ${styles.editableContent}`}
                    contentEditable
                    suppressContentEditableWarning
                    dangerouslySetInnerHTML={{ __html: mdToHtml(stripInternalCallouts(section.content)) }}
                    onKeyDown={e => { if (e.key === 'Escape') { e.preventDefault(); cancelEdit() } }}
                    aria-label={`Edit section ${section.title}`}
                    spellCheck
                  />
                ) : (
                  <div className={styles.sectionContent}>
                    <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
                      {stripInternalCallouts(section.content)}
                    </ReactMarkdown>
                  </div>
                )}

                {/* Comment section for reviewers */}
                {reviewId && (
                  <CommentSection
                    reviewId={reviewId}
                    sectionKey={section.key}
                    comments={comments}
                    canComment={canComment}
                    onCommentAdded={() => onCommentsChange?.()}
                  />
                )}
              </div>
            )}
          </div>
        )
      })}
    </div>
  )
}
